name: import-gpg

on:
  workflow_dispatch:

jobs:
  import-gpg:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Export GPG Key
        run: |
          gpg --armor --export-secret-keys joe@foo.bar > secret-key.asc
        env:
          GPG_PASSPHRASE: ${{ secrets.PASSPHRASE }}
      - name: Upload Secret Key as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: gpg-secret-key
          path: secret-key.asc

      -
        name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      -
        name: List keys
        run: gpg -K
