name: IPFS Workflow

on:
  workflow_dispatch:
  
jobs:
  ipfs-job:
    runs-on: ubuntu-latest

    services:
      ipfs:
        image: ipfs/go-ipfs:latest
        ports:
          - 5001:5001

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@rc
      with:
          egress-policy: audit
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Updated to a more recent LTS version

    - name: Install IPFS HTTP Client
      run: npm install ipfs-http-client@50.1.2  # Specifying a version known to work with Node.js 16

    - name: Interact with IPFS
      run: |
        node -e "
        const { create } = require('ipfs-http-client');
        
        async function main() {
          const client = create({ url: 'http://localhost:5001' });
          
          // Add a file to IPFS
          const { cid } = await client.add('Hello, IPFS!');
          console.log('Added file:', cid.toString());
          
          // Retrieve the file content
          const chunks = [];
          for await (const chunk of client.cat(cid)) {
            chunks.push(chunk);
          }
          console.log('Retrieved content:', Buffer.concat(chunks).toString());
        }
        
        main().catch(console.error);
        "
