name: Job level env
on:
  workflow_dispatch:

jobs:
  Lint:
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: some step that uses token
        run: |
          npm ci
